### ISSUE TITLE
argmax instead of max

### ISSUE THREAD

**Issue by rafaelvalle** [rastarobbie/mnist-adversarial-examples#1]
In [line 83](https://github.com/robertlacok/mnist-adversarial-examples/blob/master/adversarial_net.py#L83) do you mean argmax instead of max?

**Comment by robertlacok** [comment]
Thanks, you're right.   

It also seems like it shouldn't have worked with max at all, so it makes me wonder how the resulting accuracies looked reasonable in the first place.
